apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
  namespace: dtss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - name: couchdb
        image: couchdb:3.3.3
        ports:
        - containerPort: 5984
        env:
        - name: COUCHDB_USER
          value: "admin"
        - name: COUCHDB_PASSWORD
          value: "password"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: couchdb-data
          mountPath: /opt/couchdb/data
      volumes:
      - name: couchdb-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: couchdb-service
  namespace: dtss
spec:
  ports:
  - port: 5984
    targetPort: 5984
  selector:
    app: couchdb
  type: ClusterIP
